package com.nexuszero.mt.core;
import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;import java.util.regex.*;
public final class UniversalAnalyzer{
 private UniversalAnalyzer(){}
 static final Pattern URL=Pattern.compile("(?i)\\b(?:https?|wss?)://[^\\s\\\"'<>\\)\\]]+"),DOM=Pattern.compile("(?i)(?<![/@])\\b(?:[a-z0-9-]+\\.)+[a-z]{2,63}\\b"),IP=Pattern.compile("\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"),KEY=Pattern.compile("[\\\"']([A-Za-z_$][\\w$.-]{1,80})[\\\"']\\s*:");
 public static String analyze(String name,String s){StringBuilder o=new StringBuilder("NEXUS FULL INVESTIGATION\nFormat: "+FormatRegistry.detect(name,s)+"\nSHA-256: "+sha(s)+"\n\n");sec(o,"URL / WS",m(URL,s,300));sec(o,"DOMAIN",m(DOM,s,300));sec(o,"IP CANDIDATE",m(IP,s,150));sec(o,"FIELD CONTRACT CANDIDATE",g(KEY,s,1,400));String l=s.toLowerCase(Locale.ROOT);sig(o,l,"WebSocket","newwebsocket","websocketlistener","wss://","onmessage");sig(o,l,"Centrifugo","centrifugo","/connection/websocket","subscribe","publish");sig(o,l,"HTTP/API","okhttp","retrofit","authorization","bearer","baseurl");sig(o,l,"Serialization","protobuf","parsefrom","msgpack","messagepack","cbor");sig(o,l,"Native/JNI","jni_onload","system.loadlibrary","libil2cpp.so","global-metadata.dat");o.append("\nPOLICY: STATIC_SIGNAL/CANDIDATE != runtime fact. UNKNOWN is fingerprint-preserved.\n");return o.toString();}
 public static String strings(String s){Matcher m=Pattern.compile("[\\x20-\\x7e]{4,}").matcher(s);StringBuilder o=new StringBuilder("STRINGS\n");int n=0;while(m.find()&&n++<1500)o.append(m.group()).append('\n');return o.toString();}
 public static String hex(String s){byte[]b=s.getBytes(StandardCharsets.UTF_8);StringBuilder o=new StringBuilder();for(int i=0;i<b.length&&i<65536;i+=16){o.append(String.format(Locale.ROOT,"%08x  ",i));for(int j=0;j<16;j++)o.append(i+j<b.length?String.format(Locale.ROOT,"%02x ",b[i+j]&255):"   ");o.append('\n');}return o.toString();}
 public static String entropy(String s){byte[]b=s.getBytes(StandardCharsets.ISO_8859_1);if(b.length==0)return"Entropy: 0";int[]c=new int[256];for(byte x:b)c[x&255]++;double h=0;for(int n:c)if(n>0){double p=(double)n/b.length;h-=p*(Math.log(p)/Math.log(2));}return String.format(Locale.ROOT,"Entropy: %.4f bits/byte\nSHA-256: %s",h,sha(s));}
 static void sig(StringBuilder o,String s,String t,String...n){List<String>h=new ArrayList<>();for(String x:n)if(s.contains(x))h.add(x);if(!h.isEmpty())o.append("SIGNAL ").append(t).append(" [STATIC_SIGNAL]\n  ").append(String.join(", ",h)).append("\n\n");}
 static LinkedHashSet<String>m(Pattern p,String s,int z){Matcher x=p.matcher(s);LinkedHashSet<String>r=new LinkedHashSet<>();while(x.find()&&r.size()<z)r.add(x.group());return r;}static LinkedHashSet<String>g(Pattern p,String s,int q,int z){Matcher x=p.matcher(s);LinkedHashSet<String>r=new LinkedHashSet<>();while(x.find()&&r.size()<z)r.add(x.group(q));return r;}static void sec(StringBuilder o,String t,Collection<String>r){if(r.isEmpty())return;o.append(t).append('\n');for(String x:r)o.append("  ").append(x).append('\n');o.append('\n');}
 public static String sha(String s){try{byte[]b=MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8));StringBuilder h=new StringBuilder();for(byte x:b)h.append(String.format(Locale.ROOT,"%02x",x&255));return h.toString();}catch(Exception e){return"ERROR";}}
}